In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
vocab_size=10000

In [5]:
one_hot_rep=[one_hot(word,vocab_size)for word in sent]
        

In [6]:
one_hot_rep

[[3178, 3172, 3668, 3081],
 [3178, 3172, 3668, 8066],
 [3178, 5417, 3668, 9816],
 [2192, 6945, 4441, 5418, 5344],
 [2192, 6945, 4441, 5418, 9745],
 [723, 3178, 8139, 3668, 3770],
 [1997, 3571, 9069, 5418]]

In [7]:
#wordembdding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [8]:
sent_length=8
embed_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embed_docs)

[[   0    0    0    0 3178 3172 3668 3081]
 [   0    0    0    0 3178 3172 3668 8066]
 [   0    0    0    0 3178 5417 3668 9816]
 [   0    0    0 2192 6945 4441 5418 5344]
 [   0    0    0 2192 6945 4441 5418 9745]
 [   0    0    0  723 3178 8139 3668 3770]
 [   0    0    0    0 1997 3571 9069 5418]]


In [9]:
#feature_representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

c:\Users\Aryan Chauhan\anaconda3\envs\geoai\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embed_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step


array([[[-0.04700043,  0.047872  ,  0.02062788,  0.00755777,
          0.03906972, -0.02382898, -0.01410373, -0.04364933,
         -0.04061925, -0.04253974],
        [-0.04700043,  0.047872  ,  0.02062788,  0.00755777,
          0.03906972, -0.02382898, -0.01410373, -0.04364933,
         -0.04061925, -0.04253974],
        [-0.04700043,  0.047872  ,  0.02062788,  0.00755777,
          0.03906972, -0.02382898, -0.01410373, -0.04364933,
         -0.04061925, -0.04253974],
        [-0.04700043,  0.047872  ,  0.02062788,  0.00755777,
          0.03906972, -0.02382898, -0.01410373, -0.04364933,
         -0.04061925, -0.04253974],
        [ 0.03124279, -0.03288554,  0.03733571,  0.01500363,
         -0.02017752, -0.02679105,  0.01746972,  0.02525194,
          0.04673037, -0.01494111],
        [ 0.0419088 , -0.01303539, -0.03637153,  0.04329709,
         -0.02780308,  0.02705857, -0.01453312, -0.02220858,
          0.03065692,  0.03301475],
        [ 0.04288535,  0.02747789,  0.04323817,  0.0

In [13]:
embed_docs[0]


array([   0,    0,    0,    0, 3178, 3172, 3668, 3081], dtype=int32)

In [18]:
print(model.predict(embed_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
[[[-0.04700043  0.047872    0.02062788  0.00755777  0.03906972
   -0.02382898 -0.01410373 -0.04364933 -0.04061925 -0.04253974]
  [-0.04700043  0.047872    0.02062788  0.00755777  0.03906972
   -0.02382898 -0.01410373 -0.04364933 -0.04061925 -0.04253974]
  [-0.04700043  0.047872    0.02062788  0.00755777  0.03906972
   -0.02382898 -0.01410373 -0.04364933 -0.04061925 -0.04253974]
  [-0.04700043  0.047872    0.02062788  0.00755777  0.03906972
   -0.02382898 -0.01410373 -0.04364933 -0.04061925 -0.04253974]
  [ 0.03124279 -0.03288554  0.03733571  0.01500363 -0.02017752
   -0.02679105  0.01746972  0.02525194  0.04673037 -0.01494111]
  [ 0.0419088  -0.01303539 -0.03637153  0.04329709 -0.02780308
    0.02705857 -0.01453312 -0.02220858  0.03065692  0.03301475]
  [ 0.04288535  0.02747789  0.04323817  0.02743684  0.00053623
   -0.04337094  0.00090118 -0.03599215  0.02388421  0.00287328]
  [-0.01523064 -0.03210042  0.02663125 -0.02362484  0.02372015
    0.0332