In [162]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [163]:
from sklearn.datasets import make_classification

In [164]:
X,Y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [165]:
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)

In [166]:
from sklearn.model_selection import train_test_split

In [167]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

In [168]:
from sklearn.linear_model import LogisticRegression

In [169]:
Log=LogisticRegression()

In [170]:
from sklearn.preprocessing import StandardScaler

In [171]:
Scale=StandardScaler()
X_train

,0,1,2,3,4,5,6,7,8,9
82,-1.012322,0.281230,-0.875123,1.489599,-1.743673,0.156823,1.205832,1.154694,1.182599,-1.270362
991,-0.021011,0.747445,-0.038709,0.297876,-0.081894,0.991191,0.087778,-0.104358,-0.042586,0.450156
789,0.376070,0.333860,0.249581,1.431367,-0.039307,-0.134497,-0.217304,-1.312219,-0.686077,1.081767
894,1.400593,-1.517174,1.325891,0.750579,-0.569833,0.329509,-2.019915,-1.130069,-1.260049,-0.416194
398,1.035994,0.349650,1.001118,-1.564803,-1.008555,-1.962626,-1.556339,-0.263448,-0.865449,0.095344
...,...,...,...,...,...,...,...,...,...,...
106,0.582967,-0.925425,0.422577,0.255384,-1.013896,0.085687,-0.445852,-0.408101,-0.946922,-0.895346
270,-0.538786,1.534482,-0.635001,1.122374,1.096547,-2.191254,1.158654,0.543391,0.076465,-0.459765
860,0.040915,0.427963,-0.002353,1.723075,-0.160560,-0.555286,0.066475,-1.922772,-0.171048,1.639257
435,0.339379,-0.640154,0.252540,1.483744,-1.085748,0.029796,-0.279510,-1.399228,-0.529912,-0.734811


In [172]:
X_train=Scale.fit_transform(X_train)
X_test=Scale.transform(X_test)

In [173]:
Model=Log.fit(X_train,Y_train)

c:\Users\Aryan Chauhan\anaconda3\envs\sklearn-env\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [174]:
Model.intercept_

array([-0.01099125])

In [175]:
Model.coef_

array([[-0.51291798,  0.13154552, -1.16504276,  0.06663814, -0.05264942,
        -0.27600915,  1.62920406, -0.01414384, -1.0353302 ,  0.08946867]])

In [176]:
y_pred=Model.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0])

In [177]:
Model.predict_proba(X_test)

array([[7.80078228e-01, 2.19921772e-01],
       [3.36386322e-02, 9.66361368e-01],
       [6.51830039e-01, 3.48169961e-01],
       [7.90489878e-02, 9.20951012e-01],
       [9.73743073e-01, 2.62569272e-02],
       [4.06727229e-02, 9.59327277e-01],
       [9.77079104e-01, 2.29208963e-02],
       [9.51363644e-01, 4.86363555e-02],
       [7.96071398e-01, 2.03928602e-01],
       [6.80253449e-01, 3.19746551e-01],
       [9.08730390e-01, 9.12696103e-02],
       [2.51335494e-01, 7.48664506e-01],
       [5.20727427e-01, 4.79272573e-01],
       [2.12211227e-01, 7.87788773e-01],
       [7.85533723e-01, 2.14466277e-01],
       [9.41070503e-01, 5.89294967e-02],
       [2.67726951e-02, 9.73227305e-01],
       [3.46005465e-01, 6.53994535e-01],
       [3.19683378e-01, 6.80316622e-01],
       [1.99320113e-01, 8.00679887e-01],
       [4.97667946e-01, 5.02332054e-01],
       [9.60993187e-01, 3.90068125e-02],
       [1.93338658e-01, 8.06661342e-01],
       [7.86896987e-01, 2.13103013e-01],
       [8.649519

Classification Metrics

In [178]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [179]:
acc=accuracy_score(Y_test,y_pred)
cm=confusion_matrix(Y_test,y_pred)
cr=classification_report(Y_test,y_pred)
print(acc)
print(cm)
print(cr)

0.84
[[ 98  15]
 [ 25 112]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.83       113
           1       0.88      0.82      0.85       137

    accuracy                           0.84       250
   macro avg       0.84      0.84      0.84       250
weighted avg       0.84      0.84      0.84       250



Hyperparamter Tunning & Cross Validation

In [180]:
Logistic=LogisticRegression()
penalty1=['L2','L1','ElasticNet']
c=[100,10,1.0,0.1,0.01]
Solver=['newton-cg','lbfgs','liblinear','sag','saga']

In [181]:
param=dict(penalty=penalty1,C=c,solver=Solver)

In [182]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

Multiclass Classification

In [183]:
X1,Y1=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=42)

In [184]:
X1_train,X1_test,Y1_train,Y1_test=train_test_split(X1,Y1,test_size=0.30,random_state=42)

In [185]:
Logistic=LogisticRegression()

In [186]:
Logistic.fit(X1_train,Y1_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [187]:
y_pred_over=Logistic.predict(X1_test)

In [189]:
accLog=accuracy_score(Y1_test,y_pred_over)
cmLog=confusion_matrix(Y1_test,y_pred_over)
crLog=classification_report(Y1_test,y_pred_over)
print(accLog)
print(cmLog)
print(crLog)

0.7033333333333334
[[76 20  7]
 [25 48 23]
 [ 2 12 87]]
              precision    recall  f1-score   support

           0       0.74      0.74      0.74       103
           1       0.60      0.50      0.55        96
           2       0.74      0.86      0.80       101

    accuracy                           0.70       300
   macro avg       0.69      0.70      0.69       300
weighted avg       0.70      0.70      0.70       300

