In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,Y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [4]:
X=pd.DataFrame(X)
Y=pd.DataFrame(Y)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
Log=LogisticRegression()

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
Scale=StandardScaler()
X_train

,0,1,2,3,4,5,6,7,8,9
82,-1.012322,0.281230,-0.875123,1.489599,-1.743673,0.156823,1.205832,1.154694,1.182599,-1.270362
991,-0.021011,0.747445,-0.038709,0.297876,-0.081894,0.991191,0.087778,-0.104358,-0.042586,0.450156
789,0.376070,0.333860,0.249581,1.431367,-0.039307,-0.134497,-0.217304,-1.312219,-0.686077,1.081767
894,1.400593,-1.517174,1.325891,0.750579,-0.569833,0.329509,-2.019915,-1.130069,-1.260049,-0.416194
398,1.035994,0.349650,1.001118,-1.564803,-1.008555,-1.962626,-1.556339,-0.263448,-0.865449,0.095344
...,...,...,...,...,...,...,...,...,...,...
106,0.582967,-0.925425,0.422577,0.255384,-1.013896,0.085687,-0.445852,-0.408101,-0.946922,-0.895346
270,-0.538786,1.534482,-0.635001,1.122374,1.096547,-2.191254,1.158654,0.543391,0.076465,-0.459765
860,0.040915,0.427963,-0.002353,1.723075,-0.160560,-0.555286,0.066475,-1.922772,-0.171048,1.639257
435,0.339379,-0.640154,0.252540,1.483744,-1.085748,0.029796,-0.279510,-1.399228,-0.529912,-0.734811


In [11]:
X_train=Scale.fit_transform(X_train)
X_test=Scale.transform(X_test)

In [12]:
Model=Log.fit(X_train,Y_train)

c:\Users\Aryan Chauhan\anaconda3\envs\sklearn-env\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
Model.intercept_

array([-0.01099125])

In [14]:
Model.coef_

array([[-0.51291798,  0.13154552, -1.16504276,  0.06663814, -0.05264942,
        -0.27600915,  1.62920406, -0.01414384, -1.0353302 ,  0.08946867]])

In [16]:
y_pred=Model.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0])

In [17]:
Model.predict_proba(X_test)

array([[7.80078228e-01, 2.19921772e-01],
       [3.36386322e-02, 9.66361368e-01],
       [6.51830039e-01, 3.48169961e-01],
       [7.90489878e-02, 9.20951012e-01],
       [9.73743073e-01, 2.62569272e-02],
       [4.06727229e-02, 9.59327277e-01],
       [9.77079104e-01, 2.29208963e-02],
       [9.51363644e-01, 4.86363555e-02],
       [7.96071398e-01, 2.03928602e-01],
       [6.80253449e-01, 3.19746551e-01],
       [9.08730390e-01, 9.12696103e-02],
       [2.51335494e-01, 7.48664506e-01],
       [5.20727427e-01, 4.79272573e-01],
       [2.12211227e-01, 7.87788773e-01],
       [7.85533723e-01, 2.14466277e-01],
       [9.41070503e-01, 5.89294967e-02],
       [2.67726951e-02, 9.73227305e-01],
       [3.46005465e-01, 6.53994535e-01],
       [3.19683378e-01, 6.80316622e-01],
       [1.99320113e-01, 8.00679887e-01],
       [4.97667946e-01, 5.02332054e-01],
       [9.60993187e-01, 3.90068125e-02],
       [1.93338658e-01, 8.06661342e-01],
       [7.86896987e-01, 2.13103013e-01],
       [8.649519

Classification Metrics

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [22]:
acc=accuracy_score(Y_test,y_pred)
cm=confusion_matrix(Y_test,y_pred)
cr=classification_report(Y_test,y_pred)
print(acc)
print(cm)
print(cr)

0.84
[[ 98  15]
 [ 25 112]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.83       113
           1       0.88      0.82      0.85       137

    accuracy                           0.84       250
   macro avg       0.84      0.84      0.84       250
weighted avg       0.84      0.84      0.84       250



Hyperparamter Tunning & Cross Validation

In [29]:
Logistic=LogisticRegression()
penalty1=['L2','L1','ElasticNet']
c=[100,10,1.0,0.1,0.01]
Solver=['newton-cg','lbfgs','liblinear','sag','saga']

In [31]:
param=dict(penalty=penalty1,C=c,solver=Solver)