In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9]])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [3]:
arr[:,2:3]=1
arr

array([[1, 2, 1, 4, 5],
       [2, 3, 1, 5, 6],
       [3, 4, 1, 6, 7],
       [4, 5, 1, 7, 8],
       [5, 6, 1, 8, 9]])

In [4]:
arr1=np.array(([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],]))
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [5]:
np.fill_diagonal(arr1,0)
arr1

array([[0, 2, 3, 4, 5],
       [2, 0, 4, 5, 6],
       [3, 4, 0, 6, 7],
       [4, 5, 6, 0, 8]])

In [6]:
arr2=np.array([[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8],[4,5,6,7,8,9],[5,6,7,8,9,10],[11,12,13,14,15,16]])
arr2.shape
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16]])

In [7]:
arr2[2:5,1:4]

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [8]:
array=np.array(([1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8],[5,6,7,8,9]))
array

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [9]:
array[:,4]

array([5, 6, 7, 8, 9])

In [10]:
array1=np.array(([1,2,3],[2,3,4],[3,6,7],[5,4,3]))
array1

array([[1, 2, 3],
       [2, 3, 4],
       [3, 6, 7],
       [5, 4, 3]])

In [11]:
array2=np.array(([3,2,1],[4,3,2],[5,4,3],[6,5,4]))
array2

array([[3, 2, 1],
       [4, 3, 2],
       [5, 4, 3],
       [6, 5, 4]])

In [12]:
array1*array2

array([[ 3,  4,  3],
       [ 8,  9,  8],
       [15, 24, 21],
       [30, 20, 12]])

In [13]:
array1+array2
array1/array2
array1-array2

array([[-2,  0,  2],
       [-2,  0,  2],
       [-2,  2,  4],
       [-1, -1, -1]])

In [14]:
arrayops1=np.array(([1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]))
arrayops1

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
arrayops2=np.array(([1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]))
arrayops2

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.sum([arrayops1,arrayops2],axis=0)

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [17]:
np.sum([arrayops1,arrayops2],axis=1)

array([[25, 29, 33, 37],
       [25, 29, 33, 37]])

In [18]:
arraystat1=np.array(([1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]
                     ,[5,6,7,8,9]))
arraystat1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [19]:
np.mean(arraystat1)

np.float64(5.0)

In [20]:
np.median(arraystat1)

np.float64(5.0)

In [21]:
np.std(arraystat1)

np.float64(2.0)

In [22]:
np.var(arraystat1)

np.float64(4.0)

In [23]:
arraystat2=np.array(([1,2,3],[4,5,6],[7,8,9]))
arraystat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
standard=((arraystat2-np.mean(arraystat2))/np.std(arraystat2))
standard

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [25]:
broadarray1=np.array(([1,2,3],[4,5,6],[7,8,9]))
broadarray1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
add=np.array([1,2,3])
add

array([1, 2, 3])

In [27]:
broadarray1+add

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [28]:
broadarray2=np.array(([1,2,3,4],[4,3,2,1],[5,6,7,8],[9,8,7,6]))
sub=np.array([1,2,3,4])

In [29]:
broadarray2-sub

array([[ 0,  0,  0,  0],
       [ 3,  1, -1, -3],
       [ 4,  4,  4,  4],
       [ 8,  6,  4,  2]])

In [30]:
matrix1=np.matrix('1 2 3;1 1 1;3 6 5')
matrix1

matrix([[1, 2, 3],
        [1, 1, 1],
        [3, 6, 5]])

In [31]:
np.linalg.det(matrix1)

np.float64(4.0)

In [32]:
inver=np.linalg.inv(matrix1)
inver

matrix([[-2.50000000e-01,  2.00000000e+00, -2.50000000e-01],
        [-5.00000000e-01, -1.00000000e+00,  5.00000000e-01],
        [ 7.50000000e-01,  8.32667268e-17, -2.50000000e-01]])

In [33]:
mularr1=np.array(([1,2],[3,4],[5,6]))
mularr2=np.array(([1,2,3],[6,5,3]))

In [34]:
np.dot(mularr1,mularr2)

array([[13, 12,  9],
       [27, 26, 21],
       [41, 40, 33]])

In [35]:
advarr=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [36]:
flat=advarr.flatten()
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
adv=flat.reshape(3,3)

In [38]:
advarr.reshape(1,9)
advarr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [39]:
fancyarr=np.array(([1,2,3,4,5],[5,4,3,2,1],[6,7,8,9,3],[5,7,8,2,4],[9,6,5,8,4]))
x=fancyarr.flatten()

In [40]:
index=[0,4,20,24]
x[index]

array([1, 5, 9, 4])

In [41]:
bool=np.array(([1,2,3,4],[4,3,2,1],[4,5,6,7],[9,7,6,5]))
bool

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [4, 5, 6, 7],
       [9, 7, 6, 5]])

In [42]:
mask=bool>10
fill=bool[mask]
fill

array([], dtype=int64)

In [ ]:
bool.flatten()

array([1, 2, 3, 4, 4, 3, 2, 1, 4, 5, 6, 7, 9, 7, 6, 5])